name: Java CI with Maven

on:
  pull_request:
    branches:
      - main
      - issue-*
  push:
    branches:
      - main
      - issue-*
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [17, 21]
    name: 'Build Maven Java'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: test
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
          description: 'Preview my app'
          environment: preview
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.version }}
          cache: 'maven'
      - name: Install dependencies
        run: ./mvnw install |
          mkdir -p ${{ github.workspace }}/upload/
          mv ${{ github.workspace }}/target/cucumber-report.html ${{ github.workspace }}/target/index.html
          cp ${{ github.workspace }}/target/index.html ${{ github.workspace }}/upload/
      - name: Upload S3
        uses: shallwefootball/s3-upload-action@master
        id: s3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: cucumber-bank-reports
          source_dir: ${{ github.workspace }}/upload/

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_url: https://cucumber-bank-reports.s3.us-east-1.amazonaws.com/${{steps.S3.outputs.object_key}}/index.html
          state: 'success'
          deployment_id: ${{ steps.test.outputs.deployment_id }}

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp ${{ github.workspace }}/upload/index.html s3://cucumber-bank-reports/index.html