name: Java CI with Maven

on:
  pull_request:
    branches:
      - main
      - issue-*
  push:
    branches:
      - main
      - issue-*

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        version: [ 17, 21 ]
    name: 'Build Java ${{ matrix.version }} - ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.version }}
          cache: 'maven'
      - name: Install dependencies
        run: ./mvnw install --show-version
      - name: Test
        run: ./mvnw verify