name: Java CI with Maven

on:
  pull_request:
    branches:
      - main
      - issue-*
  push:
    branches:
      - main
      - issue-*

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest]
        version: [ 17, 21 ]
    name: 'Build Java ${{ matrix.version }} - ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.version }}
          cache: 'maven'
      - name: Install dependencies
        run: ./mvnw install --show-version
      - name: Test
        run: ./mvnw verify
      - name: Upload target folder
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: |
            ${{ github.workspace }}/target
      - name: Upload S3
        uses: shallwefootball/s3-upload-action@master
        id: s3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: cucumber-bank-reports
          source_dir: ${{ github.workspace }}/target/
      - name: Link to report
        run: echo "https://cucumber-bank-reports.s3.us-east-1.amazonaws.com/${{steps.s3.outputs.object_key}}/index.html"